In [ ]:
Exercise 1: House Purchase Prediction using Decision Tree

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [2]:
data = {
    'Age':[22,25,28,35,40,45,50,23,31,37],
    'Income':[25000,30000,35000,60000,80000,90000,100000,28000,55000,70000],
    'BuyHouse':[0,0,0,1,1,1,1,0,1,1]
}

df = pd.DataFrame(data)

df

   Age  Income  BuyHouse
0   22   25000         0
1   25   30000         0
2   28   35000         0
3   35   60000         1
4   40   80000         1
5   45   90000         1
6   50  100000         1
7   23   28000         0
8   31   55000         1
9   37   70000         1

In [3]:
df.isnull().sum()

Age         0
Income      0
BuyHouse    0
dtype: int64

In [4]:
X = df[['Age','Income']]

y = df['BuyHouse']

In [5]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [6]:
model = DecisionTreeClassifier(random_state=42)

In [7]:
model.fit(X_train,y_train)

DecisionTreeClassifier(random_state=42)

In [8]:
y_pred = model.predict(X_test)

In [9]:
result = pd.DataFrame({
    'Actual':y_test,
    'Predicted':y_pred
})

print(result)

   Actual  Predicted
8       1          0
1       0          0

In [10]:
print("Accuracy:",accuracy_score(y_test,y_pred))

Accuracy: 0.5

In [11]:
print(confusion_matrix(y_test,y_pred))

[[1 0]
 [1 0]]

In [12]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.50      1.00      0.67         1
           1       0.00      0.00      0.00         1

    accuracy                           0.50         2
   macro avg       0.25      0.50      0.33         2
weighted avg       0.25      0.50      0.33         2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [13]:
new_person = pd.DataFrame({
    'Age':[32],
    'Income':[65000]
})

prediction = model.predict(new_person)

if prediction[0]==1:
    print("Will Buy House")
else:
    print("Will Not Buy House")

Will Buy House