In [4]:
from google.colab import files

uploaded = files.upload()

Saving Taxi_Trips__2013-2023_.csv to Taxi_Trips__2013-2023_.csv

In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [5]:
df = pd.read_csv("Taxi_Trips__2013-2023_.csv")

df.head()

,Trip ID,Taxi ID,Trip Start Timestamp,Trip End Timestamp,Trip Seconds,Trip Miles,Pickup Census Tract,Dropoff Census Tract,Pickup Community Area,Dropoff Community Area,...,Extras,Trip Total,Payment Type,Company,Pickup Centroid Latitude,Pickup Centroid Longitude,Pickup Centroid Location,Dropoff Centroid Latitude,Dropoff Centroid Longitude,Dropoff Centroid Location
0,c76c028ab480d974af950c49ba18583c5293bbc3,bb0f5c1220143f13ded35db05ed75af60c76f84dd79d4f...,05/24/2015 01:15:00 AM,05/24/2015 01:15:00 AM,0.0,0.0,NaN,NaN,NaN,NaN,...,0.0,9.90,Credit Card,Chicago Elite Cab Corp. (Chicago Carriag,NaN,NaN,NaN,NaN,NaN,NaN
1,490e5ed9e134e07ccf2b78189c1fc1ada7a0927f,46c35a5d6b3f0ef32ca102e6260ee9a8b1fe6c7831960f...,05/20/2015 02:30:00 PM,05/20/2015 02:30:00 PM,600.0,0.2,1.703108e+10,1.703106e+10,8.0,6.0,...,1.5,12.95,Cash,Taxi Affiliation Services,41.892508,-87.626215,POINT (-87.6262149064 41.8925077809),41.949829,-87.643965,POINT (-87.6439653703 41.949829346)
2,a066b52bab5a09ed99678ab50e38b1f12b1ee772,fb318ecb67178004b27e8a37d5214da86679b46764daf8...,05/31/2015 07:15:00 PM,05/31/2015 07:30:00 PM,960.0,2.8,1.703107e+10,1.703122e+10,7.0,22.0,...,0.0,10.05,Cash,Taxi Affiliation Services,41.922083,-87.634156,POINT (-87.6341560931 41.922082541),41.921273,-87.685082,POINT (-87.6850821101 41.92127310530001)
3,8d640cef04490b450a73155c0798c7ff10aaefde,47d8d6b084ef2deb67fdf77017136e1c46e1b14653bd3b...,04/05/2015 05:45:00 PM,04/05/2015 06:00:00 PM,840.0,0.2,1.703108e+10,1.703106e+10,8.0,6.0,...,2.0,14.65,Cash,Taxi Affiliation Services,41.898332,-87.620763,POINT (-87.6207628651 41.8983317935),41.949221,-87.651970,POINT (-87.6519703953 41.9492209135)
4,3f89cbd5110e1a15474bfd8b1ddc577dbf61efd5,391b8a389424e813c930b912f093b37fb22a4d6920f975...,05/20/2015 02:15:00 PM,05/20/2015 02:15:00 PM,0.0,0.0,NaN,NaN,NaN,NaN,...,0.0,7.74,Credit Card,Chicago Elite Cab Corp. (Chicago Carriag,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 276838 entries, 0 to 276837
Data columns (total 23 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Trip ID                     276838 non-null  object
 1   Taxi ID                     276834 non-null  object
 2   Trip Start Timestamp        276834 non-null  object
 3   Trip End Timestamp          276803 non-null  object
 4   Trip Seconds                276790 non-null  float64
 5   Trip Miles                  276833 non-null  float64
 6   Pickup Census Tract         181587 non-null  float64
 7   Dropoff Census Tract        180340 non-null  float64
 8   Pickup Community Area       239132 non-null  float64
 9   Dropoff Community Area      233734 non-null  float64
 10  Fare                        276829 non-null  float64
 11  Tips                        276829 non-null  float64
 12  Tolls                       276320 non-null  float64
 13  Extras                      276829 non-null  float64
 14  Trip Total                  276829 non-null  float64
 15  Payment Type                276833 non-null  object
 16  Company                     274660 non-null  object
 17  Pickup Centroid Latitude    239146 non-null  float64
 18  Pickup Centroid Longitude   239146 non-null  float64
 19  Pickup Centroid Location    239146 non-null  object
 20  Dropoff Centroid Latitude   234318 non-null  float64
 21  Dropoff Centroid Longitude  234318 non-null  float64
 22  Dropoff Centroid  Location  234318 non-null  object
dtypes: float64(15), object(8)
memory usage: 48.6+ MB

In [7]:
df = df[['Trip Miles', 'Trip Seconds', 'Fare']]

In [8]:
df = df.dropna()

In [9]:
df.head()

   Trip Miles  Trip Seconds   Fare
0         0.0           0.0   8.25
1         0.2         600.0  11.45
2         2.8         960.0  10.05
3         0.2         840.0  12.65
4         0.0           0.0   6.45

In [10]:
X = df[['Trip Miles', 'Trip Seconds']]

y = df['Fare']

In [11]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [12]:
model = LinearRegression()

In [13]:
model.fit(X_train, y_train)

LinearRegression()

In [14]:
y_pred = model.predict(X_test)

In [15]:
result = pd.DataFrame({
    "Actual Fare": y_test,
    "Predicted Fare": y_pred
})

print(result.head())

        Actual Fare  Predicted Fare
5181           4.65        8.145976
272135         6.75       10.034496
84154          9.85       13.140281
143837        10.05       13.257256
201634        13.75        5.999936

In [16]:
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error:", mse)
print("R2 Score:", r2)

Mean Squared Error: 68.6933365008009
R2 Score: 0.43084283388288525

In [17]:
new_trip = [[4.5, 900]]

fare = model.predict(new_trip)

print("Predicted Fare: $", round(fare[0], 2))

Predicted Fare: $ 14.78

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [ ]:
Exercise 2

In [18]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [19]:
data = {
    'Weight':[79,69,73,95,82,55,69,71,64,69],
    'Height':[1.80,1.68,1.82,1.70,1.87,1.55,1.50,1.78,1.67,1.64],
    'Age':[35,39,25,60,27,18,89,42,16,52],
    'Gender':['Male','Male','Male','Male','Male',
              'Female','Female','Female','Female','Female']
}

df = pd.DataFrame(data)

df

   Weight  Height  Age  Gender
0      79    1.80   35    Male
1      69    1.68   39    Male
2      73    1.82   25    Male
3      95    1.70   60    Male
4      82    1.87   27    Male
5      55    1.55   18  Female
6      69    1.50   89  Female
7      71    1.78   42  Female
8      64    1.67   16  Female
9      69    1.64   52  Female

In [20]:
df['Gender'] = df['Gender'].map({'Male':1,'Female':0})

df

   Weight  Height  Age  Gender
0      79    1.80   35       1
1      69    1.68   39       1
2      73    1.82   25       1
3      95    1.70   60       1
4      82    1.87   27       1
5      55    1.55   18       0
6      69    1.50   89       0
7      71    1.78   42       0
8      64    1.67   16       0
9      69    1.64   52       0

In [21]:
X = df[['Height','Age','Gender']]
y = df['Weight']

In [22]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [23]:
model = LinearRegression()

In [24]:
model.fit(X_train, y_train)

LinearRegression()

In [25]:
y_pred = model.predict(X_test)

print(y_pred)

[56.85651025 79.10576115]

In [26]:
result = pd.DataFrame({
    'Actual Weight': y_test,
    'Predicted Weight': y_pred
})

print(result)

   Actual Weight  Predicted Weight
8             64         56.856510
1             69         79.105761

In [27]:
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error:", mse)
print("R2 Score:", r2)

Mean Squared Error: 76.57792714844265
R2 Score: -11.252468343750825

In [28]:
new_person = [[1.75,24,1]]

prediction = model.predict(new_person)

print("Predicted Weight:", prediction[0])

Predicted Weight: 76.64481356828415

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(